### ISSUE TITLE
Server Ruby + Bundler não funciona mais

### ISSUE THREAD

**Issue by hunkjazz** [adammacias/bootstrapbr#13]
Fiz um primeiro fork, alguns dias atrás, e conseguia executar o servidor.

No entanto, acabei deletando o fork e criando um novo. Nesse sentido, apesar de seguir as orientações [desse artigo](https://medium.com/@adammacias/contribuindo-com-a-documenta%C3%A7%C3%A3o-do-bootstrap-em-portugu%C3%AAs-4f820677f084), não consigo mais executá-lo. Nesse sentido, o navegador apresenta a seguinte mensagem: "This site can’t be reached".

Assim, gostaria de saber se o server de vocês executam ou sou eu que estou com problemas.

**Comment by adammacias** [comment]
@JLammeer tu usa algum proxy fixo? se sim, talvez setando para auto isso se resolva. [exemplo](https://www.youtube.com/watch?v=8P9mZNIf414)

**Comment by hunkjazz** [comment]
Acabei atualizando meu SO e voltou a funcionar. No entanto, não tenho a resposta certa para a dúvida.
