### ISSUE TITLE
Quais arquivos faltam ou podem ser traduzidos?

### ISSUE THREAD

**Issue by hunkjazz** [adammacias/bootstrapbr#19]
Percebi que tem alguns arquivos fora do diretório `docs` e que possuem alguns trechos em inglês. Por isso, eu queria saber se precisam de tradução, mas não sei do que se tratam, realmente.

Esses arquivos do diretório `_data`, **precisam de tradução?**

- _data\browser-bugs.yml;
- _data\browser-features.yml;
- _data\examples.yml;
- _data\nav.yml.

**E os arquivos do diretório `_gh_pages`?** Tem vários arquivos com trechos em inglês, mas eu não sei se posso mexer neles.

No diretório `_includes`, eu achei os seguintes arquivos. **Precisa traduzir eles?**

- _includes\bugify.html;
- _includes\callout-danger-async-methods.md;
- _includes\callout-info-mediaqueries-breakpoints.md;
- _includes\callout-warning-color-assistive-technologies.md;
- _includes\callout.html;
- _includes\docs-sidebar.html;
- _includes\example.html.

Já na pasta `.github` tem o arquivo `.github\CONTRIBUTING.md`. **Ele pode ser traduzido?**

No diretório `js/tests` tem os seguintes arquivos, os quais possuem comentários e textos, em inglês. **Precisam ser traduzidos?**

- js\tests\unit\.eslintrc.json;
- js\tests\unit\alert.js;
- js\tests\unit\button.js;
- js\tests\unit\collapse.js;
- js\tests\unit\dropdown.js;
- js\tests\unit\popover.js;
- js\tests\unit\tooltip.js;
- js\tests\unit\util.js;
- js\tests\visual\alert.html;
- js\tests\visual\carousel.html;
- js\tests\visual\dropdown.html;
- js\tests\visual\modal.html;
- js\tests\index.html;
- js\tests\karma.conf.js;
- js\tests\README.md.

Já na pasta `nuget`, tem dois arquivos com textos, em inglês. **Eles precisam ser traduzidos?**

- nuget\bootstrap.nuspec;
- nuget\bootstrap.sass.nuspec.

No `diretório raiz`, eu encontrei esses arquivos com textos, em inglês. **Precisa de tradução?**

- _config.yml;
- .gitattributes;
- .gitignore;
- README.md.

Até mais, @adammacias .

**Comment by adammacias** [comment]
@JLammeer opa, vamos lá

## _data

O diretório *_data* são alguns dados que são escrito na docs, só que nem tudo dá para traduzir, por exemplo o arquivo `nav.yml` são os links do menu, só que traduzindo eles o slug muda e quebra o layout, ou regra, precisamos criar uma regra na impressão para manter o slug e alterar só o título. para exemplificar:

Está assim

```
- title: Getting started
  pages:
    - title: Introduction
    - title: Download
...
```

Temos que deixa-lo assim

```
- title: Getting started
  titleTranslate: Ponto de partida
  pages:
    - title: Introduction
      titleTranslate: Introdução
    - title: Download
      titleTranslate: Download
...
```
As cores tbm são algo que não podemos mexer, pois a docs esta usando nas classes, exemplo 

```
{% for color in site.data.theme-colors %} 
     <p class="text-{{ color.name }}{% if color.name == "light" %} bg-dark{% endif %}">.text-{{ color.name }}</p>
{% endfor %}
```
## _includes

Esses são algumas partes que são incluidas na docs, podemos traduzir, deve ter pouquissimos texto ai.

## _gh_pages, .github, js/tests, nuget e raiz

Não são necessários a tradução.

***

Qualquer dúvida só me chamar :smile:  qualquer dúvida, manda o Pull-Request e eu reviso ;)

Pode me chamar no telegram tbm. E parabéns pelo trampo, tá mto lindo sua contribuição 🥇

**Comment by hunkjazz** [comment]
> Pode me chamar no telegram tbm

Não tenho intenção de incomodar, man. Mas como faço pra te adicionar, lá?
