### ISSUE TITLE
Getting Started não expande, na side bar.

### ISSUE THREAD

**Issue by hunkjazz** [adammacias/bootstrapbr#20]
Percebi isso faz tempo, mas não pensei em reportar, mais cedo.

Quando clicamos no menu "Getting Started", ele não expande para mostrar outras opções, como é suposto.

![2](https://user-images.githubusercontent.com/35262827/42342467-8e242ab0-806c-11e8-8b49-a2fc6c69f232.png)
![1](https://user-images.githubusercontent.com/35262827/42342473-90ebe936-806c-11e8-98db-6951dca8292f.png)

**Comment by adammacias** [comment]
Corrigido ;) 
 https://github.com/bootstrapbrasil/bootstrap/commit/459d34dfc0902c2649d42879f9c7e946ef9887a1
