### ISSUE TITLE
Criar próprios arquivos do diretório examples/screenshots/

### ISSUE THREAD

**Issue by hunkjazz** [adammacias/bootstrapbr#22]
Acharia legar finalizarmos criando nossas próprias thumbnails, para a página de exemplos.

![1](https://user-images.githubusercontent.com/35262827/42361000-64d70302-80c2-11e8-8d72-de02c5bd0fb5.png)

Eu mesmo tiraria os screenshots, mas a galera do repo principal [prefere que sejam feitos no Safari](https://github.com/twbs/bootstrap/issues/26806), browser do SO que não tenho. Por isso, queria deixar isso em aberto.

**Comment by adammacias** [comment]
@JLammeer Acho que nem precisa man, acredito que as imagens já estão servindo de bom exemplo para o cara clicar e ver o exemplo completo :D haha Mas sua intenção é boa.
