### ISSUE TITLE
Problema na tradução na parte de grid

### ISSUE THREAD

**Issue by vitorlsouza** [adammacias/bootstrapbr#27]
Na tradução está escrito defset ao invés de offset:

![image](https://user-images.githubusercontent.com/24439382/44941289-a28ea580-ad70-11e8-8f09-b23f13b82459.png)

Enquanto a versão em inglês está correto.

![image](https://user-images.githubusercontent.com/24439382/44941309-01ecb580-ad71-11e8-8012-917b4a81e65b.png)

**Comment by hunkjazz** [comment]
E aí, @vitorlsouza ?!

Corrigi rapidinho e já upei os arquivos, no Github. Basta o @adammacias conferir e fazer deploy.

Da próxima vez, tu pode fazer um pull request, se achar mais rápido. 
Aqui, tem algumas instruções: [Contribuindo com a documentação do Bootstrap em Português](https://medium.com/@adammacias/contribuindo-com-a-documenta%C3%A7%C3%A3o-do-bootstrap-em-portugu%C3%AAs-4f820677f084)
