### ISSUE TITLE
A versão para download e o CDN da verção 4.1.3 desatualizada

### ISSUE THREAD

**Issue by FellipeMaia** [adammacias/bootstrapbr#32]
Na documentação ( https://getbootstrap.com.br/docs/4.1/components/modal/ ) há um botão que abre uma modal com a classe .modal-xl e funciona, porem o css do donwload e o CDN não há essa classe.

**Comment by hunkjazz** [comment]
Desculpa a demora, @FellipeMaia!

Este erro realmente existe, mas tem origem lá na documentação original. Portanto, não é culpa dos tradutores.

Por isso, penso que não vale apena tentar consertar através deste projeto. Talvez, seja o caso de criar um issue no [repositório oficial](https://github.com/twbs/bootstrap).

---

Caso você ou mais alguém queira resolver este problema: atualizar para versão 4.2 é uma solução.

---

Qualquer coisa, comente que reabro o issue e discutimos mais.
