### ISSUE TITLE
Exemplo formulário

### ISSUE THREAD

**Issue by Quessada** [adammacias/bootstrapbr#36]
No exemplo de formulários da v4.1 (não vi das outras) no placeholder do exemplo de input está a classe de vocês  ".form-control-lg" e ".form-control-sm". Acho que não era a intenção de vocês, então se tiverem interesse de fazer a mudança para respectivamente "Input Grande" e "Input Pequeno".
![image](https://user-images.githubusercontent.com/39509253/77490569-fad93c80-6e19-11ea-8ced-03415188a0f9.png)

[https://getbootstrap.com.br/docs/4.1/components/forms/](https://getbootstrap.com.br/docs/4.1/components/forms/)
Att.
Matheus S. Quessada

**Comment by hunkjazz** [comment]
E aí, @Quessada ?!

Na verdade, os dois _placeholders_ **devem** possuir os valores das classes, realmente.

Acontece que, na [versão original](https://getbootstrap.com/docs/4.1/components/forms/#sizing) da documentação, este mesmo padrão ocorre. Por isso, não traduzimos ou substituímos, sequer.

De qualquer forma, agradeço pelo issue e peço perdão pela demora!
