### ISSUE TITLE
Precisam de ajuda?

### ISSUE THREAD

**Issue by hunkjazz** [adammacias/bootstrapbr#7]
Estou disposto para ajuda. Por isso, quero saber se posso começar a traduzir.

**Comment by adammacias** [comment]
@JLammeer sim! 👍 😀 Criei um artigo explicando como traduzir *[Contribuindo com a documentação do Bootstrap em Português](https://medium.com/@adammacias/contribuindo-com-a-documenta%C3%A7%C3%A3o-do-bootstrap-em-portugu%C3%AAs-4f820677f084)* Qualquer dúvida me avise, valeu! :)
